SELECT 
	IR_BEN_R.ben_nir_psa,
	IR_BEN_R.BEN_SEX_COD,
	IR_BEN_R.BEN_NAI_MOI,
	IR_BEN_R.BEN_RES_DPT,

	T_MCOaaC.EXE_SOI_DTD,
	T_MCOaaC.EXE_SOI_DTF,

	T_MCOaaB.DGN_PAL,
	T_MCOaaB.DGN_REL,
	T_MCOaaB.SOR_MOI,
	
	T_MCOaaD.ASS_DGN,

	T_MCOaaE.ETA_NUM
	
FROM T_MCOaaC

--Beneficiaire
INNER JOIN IR_BEN_R ON
	T_MCOaaC.NIR_ANO_17 = IR_BEN_R.ben_nir_psa

INNER JOIN T_MCOaaB ON
	T_MCOaaC.ETA_NUM = T_MCOaaB.ETA_NUM AND
	T_MCOaaC.RSA_NUM = T_MCOaaB.RSA_NUM

--Diagnostic associé
LEFT JOIN T_MCOaaD ON
	T_MCOaaB.ETA_NUM = T_MCOaaD.ETA_NUM AND
	T_MCOaaB.RSA_NUM = T_MCOaaB.RSA_NUM

--ACTE CCAM TABLE PAS DISPONIBLE
/*
LEFT JOIN T_MCOaaA ON
	T_MCOaaB.ETA_NUM = T_MCOaaA.ETA_NUM AND
	T_MCOaaB.RSA_NUM = T_MCOaaA.RSA_NUM	
*/
--Etablissement
LEFT JOIN T_MCOaaE ON
	T_MCOaaB.ETA_NUM = T_MCOaaE.ETA_NUM

ORDER BY IR_BEN_R.ben_nir_psa

--LIMIT 10